- hosts: masters
  become: yes
  tasks:
    - name: create an empty file for Kubeadm configuring
      copy:
        content: ""
        dest: /etc/kubernetes/kubeadm-config.yaml
        force: no
    
    - name: initialize the cluster (this could take some time)
      shell: kubeadm init --pod-network-cidr=192.168.0.0/16 --node-name master01 >> cluster_initialized.log
      args:
        chdir: /home/ubuntu
        creates: cluster_initialized.log

    - name: install Kubectl
      apt:
        name: kubectl
        state: present
        force: yes 

    - name: Touch file .bash_aliases
      file:
        path: /home/ubuntu/.bash_aliases
        state: touch
        mode: 0755

    - name: add alias for kubectl
      lineinfile:
        path: /home/ubuntu/.bash_aliases
        line: alias k='kubectl'

    - name: create .kube directory
      become: yes
      become_user: ubuntu
      file:
        path: $HOME/.kube
        state: directory
        mode: 0755

    - name: copy admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/ubuntu/.kube/config
        remote_src: yes
        owner: ubuntu

    - name: add KUBECONFIG
      become: yes
      become_user: ubuntu
      lineinfile:
        path: /etc/environment
        line: KUBECONFIG=/home/ubuntu/.kube/config

    - name: add master label
      shell: kubectl label node master01 node-role.kubernetes.io/master=master
      args:
        chdir: /home/ubuntu
        creates: cluster_initialized.log

    - name: install Pod network with calico
      become: yes
      become_user: ubuntu
      shell: |
              kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.25.1/manifests/tigera-operator.yaml
              kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.25.1/manifests/custom-resources.yaml
      args:
        chdir: $HOME